"""empty message

Revision ID: 10b969dff9b0
Revises:
Create Date: 2023-04-15 21:49:35.239882

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '10b969dff9b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('access', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marketplace', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'external_id')
    )
    op.create_table('interval_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('last_try_attempts', sa.Integer(), nullable=False),
    sa.Column('last_update_at', sa.Date(), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'type')
    )
    op.create_table('schedule_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_try_attempts', sa.Integer(), nullable=False),
    sa.Column('last_update_at', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_task')
    op.drop_table('interval_task')
    op.drop_table('product')
    op.drop_table('admin')
    # ### end Alembic commands ###
