"""empty message

Revision ID: ba673ffafb3b
Revises: f21090e2811b
Create Date: 2023-04-16 13:22:37.279477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba673ffafb3b'
down_revision = 'f21090e2811b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_account', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_account', 'name')
    # ### end Alembic commands ###
